name: Kernel Build (munch) - SUSFS + KSU NEXT | clang-r547379

on:
  pull_request:
  workflow_dispatch:
    inputs:
      BUILD_TITLE:
        description: 'Custom Build Title'
        required: false
      KERNEL_TREE:
        description: 'Kernel Tree'
        default: 'https://github.com/cabagekiller/pocof4'
        required: true
      KERNEL_TREE_BRANCH:
        description: 'Kernel Tree Branch'
        default: 'susfs-next'
        required: true
      CODENAME:
        description: 'Phone Codename'
        default: 'munch'
        required: true
      ANYKERNEL_URL:
        description: 'AnyKernel URL'
        default: 'https://github.com/DjSenseii1/f4aosp'
        required: false
      ANYKERNEL_BRANCH:
        description: 'AnyKernel Branch'
        default: 'main'
        required: false
      SECOND_ANYKERNEL_URL:
        description: 'Second AnyKernel URL'
        default: 'https://github.com/DjSenseii1/miui-hyperF4'
        required: false
      SECOND_ANYKERNEL_BRANCH:
        description: 'Second AnyKernel Branch'
        default: 'main'
        required: false
      UPLOAD_TO_RELEASE:
        description: 'Upload to GitHub Release'
        type: boolean
        default: false

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    # Display Inputs
    - name: Display User Inputs
      run: |
        echo "::group::User Environment Variables"
        echo "Build Title: ${{ github.event.inputs.BUILD_TITLE }}"
        echo "Kernel Tree: ${{ github.event.inputs.KERNEL_TREE }}/tree/${{ github.event.inputs.KERNEL_TREE_BRANCH }}"
        echo "Codename: ${{ github.event.inputs.CODENAME }}"
        echo "AnyKernel URL: ${{ github.event.inputs.ANYKERNEL_URL }}/tree/${{ github.event.inputs.ANYKERNEL_BRANCH }}"
        echo "Second AnyKernel URL: ${{ github.event.inputs.SECOND_ANYKERNEL_URL }}/tree/${{ github.event.inputs.SECOND_ANYKERNEL_BRANCH }}"
        echo "::endgroup::"

    # Setup Workspace
    - name: Initialize Workspace
      run: |
        mkdir workspace
        cd workspace
        echo "workspace-folder=$(pwd)" >> $GITHUB_ENV
        echo "start_time=$(date +%s)" >> $GITHUB_ENV
        echo "build_title=${{ github.event.inputs.BUILD_TITLE || github.event.inputs.CODENAME }}" >> $GITHUB_ENV

    # Install Build Dependencies
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y flex libncurses-dev build-essential bc bison libssl-dev wget libelf-dev

    # Download Clang Toolchain
    - name: Download Clang
      run: |
        wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz -O clang.tar.gz
        mkdir clang && tar -xf clang.tar.gz -C clang
        echo "tools-folder=$(pwd)/clang" >> $GITHUB_ENV
      working-directory: workspace

    # Clone Kernel Source
    - name: Clone Kernel Source
      run: |
        git clone --depth=1 ${{ github.event.inputs.KERNEL_TREE }} -b ${{ github.event.inputs.KERNEL_TREE_BRANCH }} kernel_tree
        echo "kernel-folder=$(pwd)/kernel_tree" >> $GITHUB_ENV
      working-directory: workspace

    # Build Kernel
    - name: Build Kernel
      run: |
        set -e
        set -x
        export ARCH=arm64
        export SUBARCH=arm64
        export KBUILD_BUILD_USER="aliza"
        export KBUILD_BUILD_HOST="GitHub"
        export PATH="${{ env.tools-folder }}/bin:$PATH"

        cd ${{ env.kernel-folder }}
        make O=out vendor/alioth_defconfig
        make O=out CC=clang -j$(nproc --all) LLVM=1 LLVM_IAS=1
      working-directory: workspace/kernel_tree

    # Package Kernel with AnyKernel
    - name: Package Kernel with AnyKernel
      if: ${{ success() && github.event.inputs.ANYKERNEL_URL != '' }}
      run: |
        set -e
        set -x
        cd ${{ env.kernel-folder }}/out/arch/arm64/boot
        git clone --depth=1 ${{ github.event.inputs.ANYKERNEL_URL }} -b ${{ github.event.inputs.ANYKERNEL_BRANCH }} AnyKernel3

        cp -f Image.gz AnyKernel3/
        [ -e dtb.img ] && mv dtb.img dtb && cp -f dtb AnyKernel3/dtb
        [ -e dtbo.img ] && cp -f dtbo.img AnyKernel3/

        cd AnyKernel3
        zip -r9 Kernel-${{ github.event.inputs.CODENAME }}.zip *
        mv Kernel-${{ github.event.inputs.CODENAME }}.zip ../
      working-directory: workspace/kernel_tree

    # Upload Artifacts
    - uses: actions/upload-artifact@v4
      if: ${{ success() && github.event.inputs.UPLOAD_TO_RELEASE != 'true' }}
      with:
        name: Kernel Build Artifacts
        path: |
          workspace/kernel_tree/out/arch/arm64/boot/Image.gz
          workspace/kernel_tree/out/arch/arm64/boot/dtb
          workspace/kernel_tree/out/arch/arm64/boot/dtbo.img
          workspace/kernel_tree/out/arch/arm64/boot/*.zip

    # Upload to Release
    - name: Upload to GitHub Release
      if: ${{ github.event.inputs.UPLOAD_TO_RELEASE == 'true' }}
      uses: softprops/action-gh-release@v2
      with:
        files: |
          workspace/kernel_tree/out/arch/arm64/boot/*.zip
        name: ${{ github.event.inputs.CODENAME }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          <b>${{ env.build_title }}</b>
          <b>Kernel successfully built!</b> Build took $(( $(date +%s) - ${{ env.start_time }} )) seconds.
          <b>Kernel tree</b>: ${{ github.event.inputs.KERNEL_TREE }}/tree/${{ github.event.inputs.KERNEL_TREE_BRANCH }}
          <b>Action Logs</b>: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
